title: Escola de Ver√£o CIBIT-ICNAS
description: Jekyll theme for a conference website
baseurl: ""
url: https://ricardomar.github.io/tests

theme: jekyll-nagymaros

copyright: Place Holder
indexing: false

permalink: pretty

exclude:
  - LICENSE
  - README.md
