title: Escola de Ver√£o CIBIT-ICNAS
description: Universidade de Coimbra |
baseurl: ""
url: https://ricardomar.github.io/tests

theme: jekyll-nagymaros

indexing: false

permalink: pretty

exclude:
  - LICENSE
  - README.md
