title: Escola de Ver√£&#127774; CIBIT-ICNAS
description: Universidade de Coimbra
baseurl: ""
url: https://ricardomar.github.io/tests

theme: jekyll-nagymaros

indexing: false

permalink: pretty

exclude:
  - LICENSE
  - README.md
